version: '3.8'

services:
  web:
    build: .
    ports:
      - "5004:5004"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATA_DIR=/app/data
    env_file:
      - .env
    command: python -m flask run --host=0.0.0.0 --port=5004
